compile_commands.json: Remove arguments that clang cannot understand
Got this:

    error: unknown argument: '-mno-fp-ret-in-387'
    error: unknown argument: '-mpreferred-stack-boundary=3'
    error: unknown argument: '-mskip-rax-setup'
    error: unknown argument: '-maccumulate-outgoing-args'
    error: unknown argument: '-mindirect-branch=thunk-extern'
    error: unknown argument: '-mindirect-branch-register'
    error: unknown argument: '-fno-var-tracking-assignments'
    error: unknown argument: '-fconserve-stack'
    warning: optimization flag '-falign-jumps=1' is not supported [-Wignored-optimization-argument]
    warning: optimization flag '-falign-loops=1' is not supported [-Wignored-optimization-argument]
    warning: optimization flag '-fmerge-constants' is not supported [-Wignored-optimization-argument]
    warning: argument unused during compilation: '--param=allow-store-data-races=0' [-Wunused-command-line-argument]
    warning: unknown warning option '-Wno-frame-address'; did you mean '-Wno-address'? [-Wunknown-warning-option]
    warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Wunknown-warning-option]
    warning: unknown warning option '-Werror=designated-init' [-Wunknown-warning-option]

Ran this:

    sed -Ei 's/ -mno-fp-ret-in-387//g' compile_commands.json
    sed -Ei 's/ -mpreferred-stack-boundary=3//g' compile_commands.json
    sed -Ei 's/ -mskip-rax-setup//g' compile_commands.json
    sed -Ei 's/ -maccumulate-outgoing-args//g' compile_commands.json
    sed -Ei 's/ -mindirect-branch=thunk-extern//g' compile_commands.json
    sed -Ei 's/ -mindirect-branch-register//g' compile_commands.json
    sed -Ei 's/ -fno-var-tracking-assignments//g' compile_commands.json
    sed -Ei 's/ -fconserve-stack//g' compile_commands.json
    sed -Ei 's/ -falign-jumps=1//g' compile_commands.json
    sed -Ei 's/ -falign-loops=1//g' compile_commands.json
    sed -Ei 's/ -fmerge-constants//g' compile_commands.json
    sed -Ei 's/ --param=allow-store-data-races=0//g' compile_commands.json
    sed -Ei 's/ --param=allow-store-data-races=0//g' compile_commands.json
    sed -Ei 's/-Wno-frame-address/-Wno-address/g' compile_commands.json
    sed -Ei 's/-Wno-unused-but-set-variable/-Wno-unused-const-variable/g' compile_commands.json
    sed -Ei 's/ -Werror=designated-init//g' compile_commands.json